version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: smarthire-backend
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
      - ../data:/app/data
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload

  ngrok:
    image: wernight/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN:-}
      NGROK_REGION: ${NGROK_REGION:-in}
      NGROK_PORT: backend:8000
    depends_on:
      - backend
